name: go
on: [push]
env:
  GO111MODULE: on
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2-beta
        with:
          go-version: "1.13.8"

      - uses: actions/checkout@v2

      - run: go mod download

      - run: go test -race ./...

      - run: curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.23.6

      - run: $(go env GOPATH)/bin/golangci-lint run ./...
